import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {argumentsFor,website,inside} from './preview-server.mjs';import {exportPortfolio,validateGLB,validateFraming} from './portfolio-library.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function build({out,handbook,library=null,publicPortfolio=null,overlay=false}){out=path.resolve(out);handbook=path.resolve(handbook);if(out===website||inside(out,website)||inside(website,out))throw Error('Output must be outside the website repository');const manifest=JSON.parse(fs.readFileSync(path.join(handbook,'manifest.json'),'utf8'));if(manifest.mode!=='public'||manifest.base_path!=='/sbox/handbook/')throw Error('Use a public-filtered handbook export');fs.mkdirSync(out,{recursive:true});for(const name of ['assets','terms'])fs.cpSync(path.join(website,name),path.join(out,name),{recursive:true});const destination=path.join(out,'sbox/handbook');if(!overlay&&destination!==handbook){if(fs.existsSync(destination))throw Error('Existing handbook output: select a fresh directory');fs.cpSync(handbook,destination,{recursive:true});}const theme=path.join(overlay?handbook:destination,'assets/site.css');const canonical=fs.readFileSync(theme,'utf8').replace(/\r\n/g,'\n'),studio=fs.readFileSync(path.join(out,'assets/design.css'),'utf8').replace(/\r\n/g,'\n');if(studio!==canonical)throw Error('Shared stylesheet drift: synchronise presentation assets first');fs.writeFileSync(path.join(out,'assets/design.css'),canonical);if(library&&publicPortfolio)throw Error('Choose either a private library or a public portfolio');const entries=publicPortfolio?copyPublicPortfolio(publicPortfolio,out):exportPortfolio(library?path.resolve(library):null,out);let page=fs.readFileSync(path.join(website,'index.html'),'utf8');if(entries.length){const markup=entries.map(row=>`<article class="portfolio-piece"><h3>${escape(row.title)}</h3><p>${escape(row.description)}</p><p class="asset-credit">${escape(row.credit)}</p><noscript><p>Enable JavaScript to inspect the model in 3D.</p></noscript></article>`).join('');page=page.replace(/<div data-portfolio>[\s\S]*?<\/div>/,()=>'<div data-portfolio>'+markup+'</div>');}fs.writeFileSync(path.join(out,'index.html'),page);return{website_source:website,handbook_source:handbook,out,snapshot:manifest.snapshot.snapshot_id,published:false,overlay};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const args=argumentsFor();if(!args.out||!args.handbook)throw Error('--out and --handbook required');console.log(JSON.stringify(build({out:args.out,handbook:args.handbook,library:args.library,publicPortfolio:args['public-portfolio'],overlay:args.overlay==='true'}),null,2));}

export function copyPublicPortfolio(source,out){
 source=fs.realpathSync(source);const rows=JSON.parse(fs.readFileSync(path.join(source,'index.json'),'utf8'));if(!Array.isArray(rows)||rows.length>100)throw Error('Invalid public portfolio');
 const entries=rows.map(row=>{if(!/^\/portfolio\/models\/[0-9a-f-]{36}\.glb$/.test(row.model)||!['title','description','credit'].every(key=>typeof row[key]==='string'))throw Error('Invalid public model entry');const file=path.join(source,row.model.slice('/portfolio/'.length)),real=fs.realpathSync(file);if(!inside(source,real)||fs.lstatSync(file).isSymbolicLink())throw Error('Unsafe public model path');const data=fs.readFileSync(real);validateGLB(data);const entry={model:row.model,title:row.title,description:row.description,credit:row.credit,exposure:Number(row.exposure),bytes:data.length};if(!Number.isFinite(entry.exposure)||entry.exposure<.2||entry.exposure>3)throw Error('Invalid model exposure');if(row.framing)entry.framing=validateFraming(row.framing);return {entry,data};});
 exportPortfolio(null,out);for(const {entry,data}of entries)fs.writeFileSync(path.join(out,entry.model.slice(1)),data);const result=entries.map(item=>item.entry);fs.writeFileSync(path.join(out,'portfolio/index.json'),JSON.stringify(result));return result;
}
