import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {createServer} from 'vite';import {website,safeFile,send,mime} from './preview-server.mjs';import {exportPortfolio} from './portfolio-library.mjs';
const reference=process.env.PIXELQUBED_REFERENCE_WORKTREE||'P:/Git/bottled-up/.sbox-reference/design-worktree';
const original=process.env.PIXELQUBED_HANDBOOK_EXPORT||'P:/Git/bottled-up/.sbox-reference/design-review-20260910/integrated/sbox/handbook';
const preview=process.env.PIXELQUBED_PREVIEW_DIR||'P:/Git/bottled-up/.sbox-reference/design-refinement-20260910/preview';
const library=process.env.PIXELQUBED_LIBRARY||'P:/Git/bottled-up/.sbox-reference/portfolio-library';
const python=process.env.PIXELQUBED_PYTHON||'C:/Users/PixelQubed/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const presentation=path.join(reference,'tools/sbox_reference/presentation/design.css'),handbook=path.join(preview,'sbox/handbook');fs.mkdirSync(preview,{recursive:true});exportPortfolio(library,preview);
function regenerate(){return new Promise((resolve,reject)=>{const code='from pathlib import Path; from tools.sbox_reference.preview_site import preview_site; import sys; preview_site(Path(sys.argv[1]),Path(sys.argv[2]),"method:Sandbox.CameraComponent:RenderToTexture(Sandbox.Texture,Sandbox.Rendering.ViewSetup)")';const child=spawn(python,['-B','-c',code,original,handbook],{cwd:reference,windowsHide:true,stdio:['ignore','pipe','pipe']});let error='';child.stderr.on('data',data=>error+=data);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(error||'Handbook preview failed')));});}
await regenerate();fs.copyFileSync(presentation,path.join(website,'assets/design.css'));
let reloadTimer,regenerating=false,pending=false;
const server=await createServer({root:website,configFile:false,cacheDir:path.join(preview,'.vite'),appType:'mpa',resolve:{alias:{three:path.join(website,'assets/vendor/three/build/three.module.js')}},optimizeDeps:{noDiscovery:true,exclude:['three']},server:{host:'127.0.0.1',port:5173,strictPort:true,fs:{strict:true,allow:[website],deny:['**/editor/**','**/*.py','**/dev.mjs','**/portfolio-library.mjs','**/build-preview.mjs','**/preview-server.mjs','**/package*.json','**/tests/**']}},plugins:[{name:'pixelqubed-handbook-preview',configureServer(server){
 server.middlewares.use(async(request,response,next)=>{try{const route=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname);if(/^\/(editor(?:\/|$)|library(?:\/|$)|api\/|portfolio.library|build.preview|preview.server|dev\.mjs|package|README|tests\/)/.test(route)){send(response,404,{});return;}if(route.startsWith('/portfolio/')){const file=safeFile(preview,route.slice(1));if(!file){send(response,404,{});return;}send(response,200,fs.readFileSync(file),mime[path.extname(file)]);return;}if(route.startsWith('/sbox/handbook/')){const relative=route.slice('/sbox/handbook/'.length)||'index.html',file=safeFile(handbook,relative)||safeFile(original,relative);if(!file){send(response,404,{});return;}if(file.endsWith('.html')){send(response,200,await server.transformIndexHtml(route,fs.readFileSync(file,'utf8')),'text/html; charset=utf-8');return;}send(response,200,fs.readFileSync(file),mime[path.extname(file)]||'application/octet-stream');return;}next();}catch(error){send(response,500,{error:'Preview rendering failed'});console.error(error.message);}});
 const refDir=path.join(reference,'tools/sbox_reference');server.watcher.add([presentation,path.join(refDir,'presentation/interactions.js'),...['export_site.py','site_theme.py','site_flow.js','site_flow.css','preview_site.py'].map(name=>path.join(refDir,name)),path.join(library,'library.json')]);
 server.watcher.on('change',file=>{const normal=file.replaceAll('\\','/');if(normal===presentation.replaceAll('\\','/')){fs.copyFileSync(presentation,path.join(website,'assets/design.css'));fs.copyFileSync(presentation,path.join(handbook,'assets/site.css'));server.ws.send({type:'full-reload',path:'*'});return;}if(normal===path.join(library,'library.json').replaceAll('\\','/')){exportPortfolio(library,preview);server.ws.send({type:'full-reload',path:'*'});return;}if(normal.startsWith(refDir.replaceAll('\\','/'))){clearTimeout(reloadTimer);reloadTimer=setTimeout(async()=>{if(regenerating){pending=true;return;}regenerating=true;try{do{pending=false;await regenerate();}while(pending);server.ws.send({type:'full-reload',path:'*'});console.log('Handbook representative preview refreshed.');}catch(error){console.error(error.message);}finally{regenerating=false;}},200);}else if(/assets\/(studio|qube-model|neural-backdrop)\.js$/.test(normal))server.ws.send({type:'full-reload',path:'*'});});
 }}]});await server.listen();server.printUrls();console.log('Persistent Vite preview: website HMR, bounded handbook refresh, private library excluded.');
