import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath} from 'node:url';
export const website=path.dirname(fileURLToPath(import.meta.url));
export function argumentsFor(argv=process.argv.slice(2)){const values={};for(let i=0;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||argv[i+1]===undefined)throw Error('Use --name value arguments');values[argv[i].slice(2)]=argv[i+1];}return values;}
export const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.jsonl':'application/x-ndjson','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary','.woff2':'font/woff2'};
export function inside(root,candidate){const rel=path.relative(path.resolve(root),path.resolve(candidate));return rel!==''&&!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel);}
export function safeFile(root,relative){const base=fs.realpathSync(root),candidate=path.resolve(base,relative);if(!inside(base,candidate)||!fs.existsSync(candidate))return null;let file=candidate;if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)||!fs.statSync(file).isFile())return null;return inside(base,fs.realpathSync(file))?file:null;}
export function send(response,status,body,type='application/json'){const data=Buffer.isBuffer(body)?body:Buffer.from(typeof body==='string'?body:JSON.stringify(body));response.writeHead(status,{'Content-Type':type,'Content-Length':data.length,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});response.end(data);}
export function createPreviewServer({root,fallback=null,port=8767}){root=path.resolve(root);if(root===website)throw Error('Serve the assembled output, not the website repository');return http.createServer((request,response)=>{try{if(!['GET','HEAD'].includes(request.method)){send(response,405,{});return;}const relative=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname).replace(/^\/+/, '');if(relative.split('/').some(x=>x.startsWith('.'))||/^(editor|api\/state|library|portfolio.library)/.test(relative)){send(response,404,{});return;}const file=safeFile(root,relative||'index.html')||(fallback?safeFile(fallback,relative||'index.html'):null);if(!file){send(response,404,{});return;}send(response,200,request.method==='HEAD'?Buffer.alloc(0):fs.readFileSync(file),mime[path.extname(file)]||'application/octet-stream');}catch{send(response,404,{});}}).listen(port,'127.0.0.1');}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const args=argumentsFor();if(!args.root)throw Error('--root is required');createPreviewServer({root:args.root,fallback:args.fallback,port:Number(args.port||8767)});console.log(`Local preview: http://127.0.0.1:${args.port||8767}/`);}
